# -  /SLGxBOTInfo/

FROM quay.io/SLGxBOT/SLGxLEADER-BOT-v1
RUN git clone https://github.com/SLGxBOT/SLGxLEADER-BOT /root/SLGxBOT
WORKDIR /root/SLGxBOT/
RUN npm install
EXPOSE 8000
CMD ["npm","start","yarn" ]
  
# -  /SLGxBOTInfo/
